#!/usr/bin/env python3
"""
Task 8: Answer Evaluation Harness

Generates answers via the full Phase 2 RAG pipeline and scores them
against gold answers using an LLM-as-judge (faithfulness scoring).

Usage:
    python3 scripts/evaluate_answers.py [--limit N]

Output:
    artifacts/eval/answers_<timestamp>.json
"""
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional
import json
import logging

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from src.data.loaders import load_qa
from src.pipeline.rag import rag_query_full, load_indices, _load_config
from src.generation.llm import _get_client

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


def _score_faithfulness_with_llm(
    gold_answer: str,
    generated_answer: str,
    llm_client,
    model: str = None,
) -> float:
    """Score faithfulness of generated answer against gold answer using LLM-as-judge.

    Args:
        gold_answer: The gold/reference answer.
        generated_answer: The answer generated by the RAG pipeline.
        llm_client: OpenAI client for calling the LLM.
        model: Optional model override.

    Returns:
        float: Faithfulness score between 0 and 1, or 0.5 if scoring fails.
    """
    if not llm_client:
        logger.warning("LLM client is None, returning fallback faithfulness score 0.5")
        return 0.5

    prompt = f"""Compare the following gold answer with the generated answer and rate the faithfulness.

Gold Answer:
{gold_answer}

Generated Answer:
{generated_answer}

Rate the faithfulness on a scale of 0.0 to 1.0 where:
- 1.0 = Generated answer is completely faithful to gold answer
- 0.7 = Generated answer is mostly faithful with minor differences
- 0.5 = Generated answer captures some key points but has significant differences
- 0.3 = Generated answer has major disagreements or missing key information
- 0.0 = Generated answer is contradictory or completely incorrect

Respond with ONLY the numerical score (e.g., 0.85). Do not include any other text."""

    try:
        response = llm_client.chat.completions.create(
            model=model or "gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=50,
            temperature=0.0,
        )
        response_text = response.choices[0].message.content or ""

        # Parse the score from response
        score = _parse_faithfulness_score(response_text)
        return score

    except Exception as e:
        logger.error(f"Error computing faithfulness score: {e}")
        return 0.5  # Fallback to neutral score on error


def _parse_faithfulness_score(response_text: str) -> float:
    """Extract a numerical score (0-1) from LLM response text.

    Args:
        response_text: The LLM response text.

    Returns:
        float: Parsed score between 0 and 1, or 0.5 if parsing fails.
    """
    import re

    response_text = response_text.strip()

    # Try to find a decimal number
    decimal_match = re.search(r"0\.\d+", response_text)
    if decimal_match:
        try:
            score = float(decimal_match.group())
            # Clamp to [0, 1]
            return max(0.0, min(1.0, score))
        except ValueError:
            pass

    # Try to find any number and normalize
    number_match = re.search(r"\d+(?:\.\d+)?", response_text)
    if number_match:
        try:
            num = float(number_match.group())
            # If it's 0 or 1, treat as integer score
            if num in (0, 1):
                return float(num)
            # If it's between 0 and 1, use as-is
            if 0 <= num <= 1:
                return num
            # If it's > 1, assume it was 0-100 scale, normalize
            if num > 1:
                return min(1.0, num / 100.0)
        except ValueError:
            pass

    logger.warning(f"Could not parse faithfulness score from: {response_text}")
    return 0.5


def evaluate_answers(
    qa_pairs: List[Dict[str, Any]] = None,
    limit: int = None,
    output_dir: Path = None,
) -> Optional[Path]:
    """Evaluate answers by generating them via the full Phase 2 pipeline.

    Args:
        qa_pairs: Optional list of QA pairs to evaluate (defaults to test split).
        limit: Optional limit on number of pairs to evaluate (for cost control).
        output_dir: Optional output directory (defaults to artifacts/eval).

    Returns:
        Path to the output JSON file, or None if evaluation failed.
    """
    # Load QA pairs if not provided
    if qa_pairs is None:
        qa_pairs = load_qa(split="test")

    if limit:
        qa_pairs = qa_pairs[:limit]

    # Load indices and config
    cfg = _load_config()
    retrieval_mode = cfg.get("retrieval", {}).get("mode", "bm25")
    load_indices(mode=retrieval_mode)

    # Get LLM client for faithfulness scoring
    llm_client = _get_client()
    llm_model = cfg.get("llm", {}).get("model", "gpt-4o-mini")

    # Evaluate each QA pair
    samples = []
    faithfulness_scores = []
    groundedness_scores = []

    logger.info(f"Evaluating {len(qa_pairs)} QA pairs...")

    for i, qa in enumerate(qa_pairs):
        if (i + 1) % 10 == 0:
            logger.info(f"  Progress: {i + 1}/{len(qa_pairs)}")

        question = qa["question"]
        gold_answer = qa.get("answer", "")

        try:
            # Generate answer via full pipeline
            result = rag_query_full(question)
            generated_answer = result["answer"]
            groundedness_score = result.get("groundedness_score")

            # Score faithfulness
            faithfulness_score = _score_faithfulness_with_llm(
                gold_answer, generated_answer, llm_client, model=llm_model
            )

            # Record sample
            sample = {
                "question": question,
                "gold_answer": gold_answer,
                "generated_answer": generated_answer,
                "faithfulness_score": faithfulness_score,
                "groundedness_score": groundedness_score,
            }
            samples.append(sample)

            faithfulness_scores.append(faithfulness_score)
            if groundedness_score is not None:
                groundedness_scores.append(groundedness_score)

        except Exception as e:
            logger.error(f"Error evaluating QA pair {i}: {e}")
            # Record a failed sample
            sample = {
                "question": question,
                "gold_answer": gold_answer,
                "generated_answer": None,
                "faithfulness_score": 0.0,
                "groundedness_score": None,
                "error": str(e),
            }
            samples.append(sample)

    # Compute summary statistics
    mean_faithfulness = (
        sum(faithfulness_scores) / len(faithfulness_scores)
        if faithfulness_scores
        else 0.0
    )
    mean_groundedness = (
        sum(groundedness_scores) / len(groundedness_scores)
        if groundedness_scores
        else 0.0
    )

    summary = {
        "num_samples": len(samples),
        "mean_faithfulness_score": mean_faithfulness,
        "mean_groundedness_score": mean_groundedness,
        "num_scored_groundedness": len(groundedness_scores),
    }

    results = {
        "timestamp": datetime.now().isoformat(),
        "config": cfg,
        "summary": summary,
        "samples": samples,
    }

    # Write results to JSON
    output_dir = output_dir or (project_root / "artifacts" / "eval")
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"answers_{timestamp}.json"

    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)

    logger.info(f"Wrote evaluation results to {output_path}")

    # Print summary
    print("\n" + "=" * 60)
    print("EVALUATION SUMMARY")
    print("=" * 60)
    print(f"Samples evaluated: {summary['num_samples']}")
    print(f"Mean faithfulness score: {summary['mean_faithfulness_score']:.4f}")
    print(f"Mean groundedness score: {summary['mean_groundedness_score']:.4f} ({summary['num_scored_groundedness']} scored)")
    print(f"Results written to: {output_path}")
    print("=" * 60 + "\n")

    return output_path


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Evaluate RAG answers against gold answers.")
    parser.add_argument("--limit", type=int, default=None, help="Evaluate only the first N QA pairs (cost control)")
    args = parser.parse_args()

    evaluate_answers(limit=args.limit)


if __name__ == "__main__":
    main()
